// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/apis/istio/v1alpha1/values_types.proto

package v1alpha1

import (
	bytes "bytes"
	fmt "fmt"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/protobuf/google/protobuf"
	_ "github.com/golang/protobuf/ptypes/duration"
	_ "k8s.io/api/core/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for AddonIngressConfig
func (this *AddonIngressConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AddonIngressConfig
func (this *AddonIngressConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ArchConfig
func (this *ArchConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ArchConfig
func (this *ArchConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CNIConfig
func (this *CNIConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CNIConfig
func (this *CNIConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CPUTargetUtilizationConfig
func (this *CPUTargetUtilizationConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CPUTargetUtilizationConfig
func (this *CPUTargetUtilizationConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CertManagerConfig
func (this *CertManagerConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CertManagerConfig
func (this *CertManagerConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Resources
func (this *Resources) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Resources
func (this *Resources) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CoreDNSConfig
func (this *CoreDNSConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CoreDNSConfig
func (this *CoreDNSConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DefaultPodDisruptionBudgetConfig
func (this *DefaultPodDisruptionBudgetConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DefaultPodDisruptionBudgetConfig
func (this *DefaultPodDisruptionBudgetConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DefaultResourcesConfig
func (this *DefaultResourcesConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DefaultResourcesConfig
func (this *DefaultResourcesConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for EgressGatewayConfig
func (this *EgressGatewayConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for EgressGatewayConfig
func (this *EgressGatewayConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for EnvoyMetricsConfig
func (this *EnvoyMetricsConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for EnvoyMetricsConfig
func (this *EnvoyMetricsConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GalleyConfig
func (this *GalleyConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GalleyConfig
func (this *GalleyConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GatewayLabelsConfig
func (this *GatewayLabelsConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GatewayLabelsConfig
func (this *GatewayLabelsConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GatewaysConfig
func (this *GatewaysConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GatewaysConfig
func (this *GatewaysConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GlobalConfig
func (this *GlobalConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GlobalConfig
func (this *GlobalConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GlobalLoggingConfig
func (this *GlobalLoggingConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GlobalLoggingConfig
func (this *GlobalLoggingConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for IngressGatewayConfig
func (this *IngressGatewayConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IngressGatewayConfig
func (this *IngressGatewayConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for IngressGatewaySdsConfig
func (this *IngressGatewaySdsConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IngressGatewaySdsConfig
func (this *IngressGatewaySdsConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for IngressGatewayZvpnConfig
func (this *IngressGatewayZvpnConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IngressGatewayZvpnConfig
func (this *IngressGatewayZvpnConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for KubernetesEnvMixerAdapterConfig
func (this *KubernetesEnvMixerAdapterConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KubernetesEnvMixerAdapterConfig
func (this *KubernetesEnvMixerAdapterConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for KubernetesIngressConfig
func (this *KubernetesIngressConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KubernetesIngressConfig
func (this *KubernetesIngressConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LoadSheddingConfig
func (this *LoadSheddingConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LoadSheddingConfig
func (this *LoadSheddingConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MTLSConfig
func (this *MTLSConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MTLSConfig
func (this *MTLSConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MeshExpansionConfig
func (this *MeshExpansionConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MeshExpansionConfig
func (this *MeshExpansionConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MixerTelemetryAdaptersConfig
func (this *MixerTelemetryAdaptersConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MixerTelemetryAdaptersConfig
func (this *MixerTelemetryAdaptersConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MixerPolicyAdaptersConfig
func (this *MixerPolicyAdaptersConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MixerPolicyAdaptersConfig
func (this *MixerPolicyAdaptersConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MixerConfig
func (this *MixerConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MixerConfig
func (this *MixerConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MixerPolicyConfig
func (this *MixerPolicyConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MixerPolicyConfig
func (this *MixerPolicyConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MixerTelemetryConfig
func (this *MixerTelemetryConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MixerTelemetryConfig
func (this *MixerTelemetryConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MultiClusterConfig
func (this *MultiClusterConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MultiClusterConfig
func (this *MultiClusterConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for NodeAgentConfig
func (this *NodeAgentConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for NodeAgentConfig
func (this *NodeAgentConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for OutboundTrafficPolicyConfig
func (this *OutboundTrafficPolicyConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for OutboundTrafficPolicyConfig
func (this *OutboundTrafficPolicyConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PilotConfig
func (this *PilotConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PilotConfig
func (this *PilotConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PilotIngressConfig
func (this *PilotIngressConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PilotIngressConfig
func (this *PilotIngressConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PilotPolicyConfig
func (this *PilotPolicyConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PilotPolicyConfig
func (this *PilotPolicyConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PilotTelemetryConfig
func (this *PilotTelemetryConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PilotTelemetryConfig
func (this *PilotTelemetryConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PortsConfig
func (this *PortsConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PortsConfig
func (this *PortsConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PrometheusConfig
func (this *PrometheusConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PrometheusConfig
func (this *PrometheusConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PrometheusMixerAdapterConfig
func (this *PrometheusMixerAdapterConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PrometheusMixerAdapterConfig
func (this *PrometheusMixerAdapterConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PrometheusSecurityConfig
func (this *PrometheusSecurityConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PrometheusSecurityConfig
func (this *PrometheusSecurityConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PrometheusServiceConfig
func (this *PrometheusServiceConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PrometheusServiceConfig
func (this *PrometheusServiceConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PrometheusServiceNodePortConfig
func (this *PrometheusServiceNodePortConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PrometheusServiceNodePortConfig
func (this *PrometheusServiceNodePortConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ProxyConfig
func (this *ProxyConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ProxyConfig
func (this *ProxyConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for EnvoyAccessLogConfig
func (this *EnvoyAccessLogConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for EnvoyAccessLogConfig
func (this *EnvoyAccessLogConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ProxyInitConfig
func (this *ProxyInitConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ProxyInitConfig
func (this *ProxyInitConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ResourcesRequestsConfig
func (this *ResourcesRequestsConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ResourcesRequestsConfig
func (this *ResourcesRequestsConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SDSConfig
func (this *SDSConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SDSConfig
func (this *SDSConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SecretVolume
func (this *SecretVolume) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SecretVolume
func (this *SecretVolume) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SecurityConfig
func (this *SecurityConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SecurityConfig
func (this *SecurityConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ServiceConfig
func (this *ServiceConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ServiceConfig
func (this *ServiceConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SidecarInjectorConfig
func (this *SidecarInjectorConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SidecarInjectorConfig
func (this *SidecarInjectorConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for StdioMixerAdapterConfig
func (this *StdioMixerAdapterConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for StdioMixerAdapterConfig
func (this *StdioMixerAdapterConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for StackdriverMixerAdapterConfig
func (this *StackdriverMixerAdapterConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for StackdriverMixerAdapterConfig
func (this *StackdriverMixerAdapterConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for StackdriverAuthConfig
func (this *StackdriverAuthConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for StackdriverAuthConfig
func (this *StackdriverAuthConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for StackdriverTracerConfig
func (this *StackdriverTracerConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for StackdriverTracerConfig
func (this *StackdriverTracerConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for StackdriverContextGraph
func (this *StackdriverContextGraph) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for StackdriverContextGraph
func (this *StackdriverContextGraph) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracerConfig
func (this *TracerConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracerConfig
func (this *TracerConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracerDatadogConfig
func (this *TracerDatadogConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracerDatadogConfig
func (this *TracerDatadogConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracerLightStepConfig
func (this *TracerLightStepConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracerLightStepConfig
func (this *TracerLightStepConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracerZipkinConfig
func (this *TracerZipkinConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracerZipkinConfig
func (this *TracerZipkinConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracingConfig
func (this *TracingConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracingConfig
func (this *TracingConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracingOpencensusConfig
func (this *TracingOpencensusConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracingOpencensusConfig
func (this *TracingOpencensusConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracingOpencensusExportersConfig
func (this *TracingOpencensusExportersConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracingOpencensusExportersConfig
func (this *TracingOpencensusExportersConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracingIngressConfig
func (this *TracingIngressConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracingIngressConfig
func (this *TracingIngressConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracingJaegerConfig
func (this *TracingJaegerConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracingJaegerConfig
func (this *TracingJaegerConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracingJaegerMemoryConfig
func (this *TracingJaegerMemoryConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracingJaegerMemoryConfig
func (this *TracingJaegerMemoryConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracingZipkinConfig
func (this *TracingZipkinConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracingZipkinConfig
func (this *TracingZipkinConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TracingZipkinNodeConfig
func (this *TracingZipkinNodeConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TracingZipkinNodeConfig
func (this *TracingZipkinNodeConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for KialiSecurityConfig
func (this *KialiSecurityConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KialiSecurityConfig
func (this *KialiSecurityConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for KialiDashboardConfig
func (this *KialiDashboardConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KialiDashboardConfig
func (this *KialiDashboardConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for KialiIngressConfig
func (this *KialiIngressConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KialiIngressConfig
func (this *KialiIngressConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for KialiConfig
func (this *KialiConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KialiConfig
func (this *KialiConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Values
func (this *Values) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Values
func (this *Values) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TypeMapStringInterface
func (this *TypeMapStringInterface) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TypeMapStringInterface
func (this *TypeMapStringInterface) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TypeSliceOfMapStringInterface
func (this *TypeSliceOfMapStringInterface) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TypeSliceOfMapStringInterface
func (this *TypeSliceOfMapStringInterface) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TypeIntOrStringForPB
func (this *TypeIntOrStringForPB) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TypeIntOrStringForPB
func (this *TypeIntOrStringForPB) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ZeroVPNConfig
func (this *ZeroVPNConfig) MarshalJSON() ([]byte, error) {
	str, err := ValuesTypesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ZeroVPNConfig
func (this *ZeroVPNConfig) UnmarshalJSON(b []byte) error {
	return ValuesTypesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ValuesTypesMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	ValuesTypesUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
