version: 2

jobs:
  test:
    docker:
      - image: gcr.io/istio-testing/circleci:2019-04-22
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/istio.io/operator
    steps:
      - checkout
      - run:
          name: Running unit tests
          command: go test -race ./...

workflows:
  version: 2
  all:
    jobs:
      - test
