apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: default
trafficManagement:
  components:
    pilot:
      common:
        values:
          traceSampling: 0.5
          keepaliveMaxServerConnectionAge: 60m
