apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  trafficManagement:
    enabled: true
    components:
      namespace: istio-foo
      pilot:
        common:
          namespace: istio-pilot
          enabled: true
      proxy:
        common:
          namespace: istio-proxy
          enabled: false
  policy:
    enabled: false
    components:
      policy:
        common:
          enabled: false

  telemetry:
    enabled: false
    components:
      telemetry:
        common:
          enabled: false

  configManagement:
    enabled: false
    components:
      galley:
        common:
          enabled: false

  autoInjection:
    enabled: false
    components:
      injector:
        common:
          enabled: false

  gateways:
    enabled: false
    components:
      ingressGateway:
        gateway:
          common:
            enabled: false
      egressGateway:
        gateway:
          common:
            enabled: false

  security:
    enabled: false
    components:
      citadel:
        common:
          enabled: false
      certManager:
        common:
          enabled: false
      nodeAgent:
        common:
          enabled: false

